development:
  adapter: postgresql
  encoding: unicode
  database: lokaj_development
  host: localhost
  pool: 5
  password: postgres
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: lokaj_test
  host: localhost
  pool: 5
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: lokaj_production
  host: localhost
  pool: 5
  password: postgres
